// Code generated by "stringer -type=TokenType,ErrType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenName-1]
	_ = x[TokenSurname-2]
	_ = x[TokenAlias-3]
	_ = x[TokenUnknown-4]
	_ = x[TokenWord-5]
	_ = x[TokenNum-6]
	_ = x[TokenArrow-7]
	_ = x[TokenEqual-8]
	_ = x[TokenPunctuation-9]
	_ = x[TokenPlus-10]
	_ = x[TokenComma-11]
	_ = x[TokenBracket-12]
	_ = x[TokenBracketLeft-13]
	_ = x[TokenBracketRight-14]
	_ = x[TokenComment-15]
	_ = x[TokenSpace-16]
	_ = x[TokenEmptyLines-17]
	_ = x[TokenNewLine-18]
	_ = x[TokenInvalid-19]
}

const _TokenType_name = "TokenNameTokenSurnameTokenAliasTokenUnknownTokenWordTokenNumTokenArrowTokenEqualTokenPunctuationTokenPlusTokenCommaTokenBracketTokenBracketLeftTokenBracketRightTokenCommentTokenSpaceTokenEmptyLinesTokenNewLineTokenInvalid"

var _TokenType_index = [...]uint8{0, 9, 21, 31, 43, 52, 60, 70, 80, 96, 105, 115, 127, 143, 160, 172, 182, 197, 209, 221}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnexpected-1]
}

const _ErrType_name = "ErrUnexpected"

var _ErrType_index = [...]uint8{0, 13}

func (i ErrType) String() string {
	i -= 1
	if i < 0 || i >= ErrType(len(_ErrType_index)-1) {
		return "ErrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrType_name[_ErrType_index[i]:_ErrType_index[i+1]]
}
